apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: business-service
  name: business-service
spec:
  ports:
  - name: "8087"
    port: 8087
    targetPort: 8087
  selector:
    io.kompose.service: business-service
