apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: config-server
    spec:
      containers:
      - env:
        - name: ANA_CONFIG_SERVER_PORT
          value: "8888"
        - name: ANA_MYSQL_HOST
          value: db
        - name: ANA_MYSQL_PASWORD
          value: mysql123
        - name: ANA_MYSQL_PORT
          value: "3306"
        - name: ANA_MYSQL_USERNAME
          value: root
        - name: ANA_SPRING_CLOUD_EUREKA_URL
          value: http://service-registry:8761
        image: projectana/config-server
        imagePullPolicy: ""
        name: config-server
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
