apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: core
  name: core
spec:
  #type: NodePort
  ports:
  - name: "9500"
    port: 9500
    targetPort: 9500
  selector:
    io.kompose.service: core
