apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "6378"
    port: 6378
    targetPort: 6379
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
