apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: service-registry
  name: service-registry
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8761
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    io.kompose.service: service-registry
