apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: service-registry
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-registry
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: service-registry
    spec:
      containers:
      - env:
        - name: ANA_SERVICE_REGISTRY_PORT
          value: "8761"
        image: projectana/service-registry
        imagePullPolicy: ""
        name: service-registry
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
